### ISSUE TITLE
Paper Update

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [Yangzhangcst/RGBD-semantic-segmentation#1]
Hello,

Just thought that this paper: Self-Supervised Model Adaptation for Multimodal Semantic Segmentation by Valada et al. might
be useful to add to this list, since they test on the NYUDv2 and SUN RGBD datasets using RGBD inputs.

https://arxiv.org/pdf/1808.03833.pdf

**Comment by Yangzhangcst** [comment]
> Hello,
> 
> Just thought that this paper: Self-Supervised Model Adaptation for Multimodal Semantic Segmentation by Valada et al. might
> be useful to add to this list, since they test on the NYUDv2 and SUN RGBD datasets using RGBD inputs.
> 
> https://arxiv.org/pdf/1808.03833.pdf

Thanks for your help. We have updated this project.

**Comment by ychenuva** [comment]
Hi,

Thanks for the great collection! 
Hope our 2019 work could help as a complement with evaluation on NYUv2 dataset. 

https://arxiv.org/abs/1910.01460

**Comment by Yangzhangcst** [comment]
> Hi,
> 
> Thanks for the great collection!
> Hope our 2019 work could help as a complement with evaluation on NYUv2 dataset.
> 
> https://arxiv.org/abs/1910.01460

Thanks for your help. We have updated this project.

**Comment by Zongwei97** [comment]
Hello,
Thanks for the github.
Thought that our work may also help for rgbd research. Depth-Adapted CNN for RGB-D cameras, ACCV 20
https://arxiv.org/pdf/2009.09976.pdf

**Comment by Yangzhangcst** [comment]
> Thanks for your help. We have updated this project.

**Comment by Yangzhangcst** [comment]
> Hello, Thanks for the github. Thought that our work may also help for rgbd research. Depth-Adapted CNN for RGB-D cameras, ACCV 20 https://arxiv.org/pdf/2009.09976.pdf

Thanks for your help. We have updated this project.
